export const imagesRound1 = [
  { type: 'cupcake', image: '/boxes/cupcake3.png' },
  { type: 'apple', image: '/boxes/red_apple.png' },
  { type: 'question_mark', image: '/boxes/question_mark4.png' },
  { type: 'cupcake', image: '/boxes/cupcake2.png' },
  { type: 'apple', image: '/boxes/green_apple.png' },
  { type: 'question_mark', image: '/boxes/question_mark2.png' },
  { type: 'question_mark', image: '/boxes/question_mark1.png' },
  { type: 'cupcake', image: '/boxes/cupcake4.png' },
]

export const imagesRound2 = [
  { type: 'heart', image: '/boxes/red_heart.png' },
  { type: 'cactus', image: '/boxes/blue_cactus.png' },
  { type: 'clock', image: '/boxes/yellow_clock.png' },
  { type: 'cactus', image: '/boxes/green_cactus.png' },
  { type: 'clock', image: '/boxes/blue_clock.png' },
  { type: 'heart', image: '/boxes/green_heart.png' },
  { type: 'heart', image: '/boxes/blue_heart.png' },
  { type: 'clock', image: '/boxes/red_clock.png' },
]

export const imagesRound3 = [
  { type: 'cupcake', image: '/boxes/cupcake2.png' },
  { type: 'sock', image: '/boxes/yellow_sock.png' },
  { type: 'hat', image: '/boxes/hat1.png' },
  { type: 'duck', image: '/boxes/green_duck.png' },
  { type: 'cupcake', image: '/boxes/cupcake3.png' },
  { type: 'sock', image: '/boxes/blue_sock.png' },
  { type: 'hat', image: '/boxes/hat2.png' },
  { type: 'duck', image: '/boxes/blue_duck.png' },
  { type: 'cupcake', image: '/boxes/cupcake4.png' },
  { type: 'sock', image: '/boxes/red_sock.png' },
]

export const imagesRound4 = [
  { type: 'pen', image: '/boxes/red_pen.png' },
  { type: 'shoe', image: '/boxes/yellow_shoe.png' },
  { type: 'scarf', image: '/boxes/green_scarf.png' },
  { type: 'pen', image: '/boxes/green_pen.png' },
  { type: 'scarf', image: '/boxes/red_scarf.png' },
  { type: 'shoe', image: '/boxes/blue_shoe.png' },
  { type: 'hat', image: '/boxes/hat2.png' },
  { type: 'scarf', image: '/boxes/blue_scarf.png' },
  { type: 'hat', image: '/boxes/hat3.png' },
  { type: 'pen', image: '/boxes/yellow_pen.png' },
]

export const imagesRound5 = [
  { type: 'sock', image: '/boxes/blue_sock.png' },
  { type: 'apple', image: '/boxes/green_apple.png' },
  { type: 'cupcake', image: '/boxes/cupcake2.png' },
  { type: 'apple', image: '/boxes/yellow__apple.png' },
  { type: 'tie', image: '/boxes/red_tie.png' },
  { type: 'cupcake', image: '/boxes/cupcake4.png' },
  { type: 'tie', image: '/boxes/blue_tie.png' },
  { type: 'question_mark', image: '/boxes/question_mark1.png' },
  { type: 'cupcake', image: '/boxes/cupcake3.png' },
  { type: 'question_mark', image: '/boxes/question_mark5.png' },
  { type: 'sock', image: '/boxes/green_sock.png' },
  { type: 'tie', image: '/boxes/yellow_tie.png' },
  { type: 'question_mark', image: '/boxes/question_mark4.png' },
  { type: 'sock', image: '/boxes/yellow_sock.png' },
]

export const imagesRound6 = [
  { type: 'tie', image: '/boxes/red_tie.png' },
  { type: 'shoe', image: '/boxes/blue_shoe.png' },
  { type: 'apple', image: '/boxes/green_apple.png' },
  { type: 'clock', image: '/boxes/blue_clock.png' },
  { type: 'strawberry', image: '/boxes/yellow_strawberry.png' },
  { type: 'shoe', image: '/boxes/green_shoe.png' },
  { type: 'strawberry', image: '/boxes/red_strawberry.png' },
  { type: 'clock', image: '/boxes/red_clock.png' },
  { type: 'apple', image: '/boxes/yellow__apple.png' },
  { type: 'tie', image: '/boxes/blue_tie.png' },
  { type: 'clock', image: '/boxes/green_clock.png' },
  { type: 'shoe', image: '/boxes/red_shoe.png' },
  { type: 'apple', image: '/boxes/red_apple.png' },
  { type: 'tie', image: '/boxes/yellow_tie.png' },
]

export const imagesRound7 = [
  { type: 'hat', image: '/boxes/hat1.png' },
  { type: 'tie', image: '/boxes/blue_tie.png' },
  { type: 'hat', image: '/boxes/hat3.png' },
  { type: 'apple', image: '/boxes/green_apple.png' },
  { type: 'question_mark', image: '/boxes/question_mark5.png' },
  { type: 'hat', image: '/boxes/hat2.png' },
  { type: 'scarf', image: '/boxes/green_scarf.png' },
  { type: 'cupcake', image: '/boxes/cupcake2.png' },
  { type: 'tie', image: '/boxes/yellow_tie.png' },
  { type: 'scarf', image: '/boxes/red_scarf.png' },
  { type: 'question_mark', image: '/boxes/question_mark2.png' },
  { type: 'cupcake', image: '/boxes/cupcake1.png' },
  { type: 'apple', image: '/boxes/yellow__apple.png' },
  { type: 'scarf', image: '/boxes/blue_scarf.png' },
  { type: 'question_mark', image: '/boxes/question_mark3.png' },
  { type: 'cupcake', image: '/boxes/cupcake3.png' },
]

export const imagesRound8 = [
  { type: 'sock', image: '/boxes/red_sock.png' },
  { type: 'bow', image: '/boxes/blue_bow.png' },
  { type: 'apple', image: '/boxes/yellow__apple.png' },
  { type: 'shoe', image: '/boxes/yellow_shoe.png' },
  { type: 'apple', image: '/boxes/green_apple.png' },
  { type: 'bow', image: '/boxes/red_bow.png' },
  { type: 'hat', image: '/boxes/hat2.png' },
  { type: 'duck', image: '/boxes/green_duck.png' },
  { type: 'duck', image: '/boxes/yellow_duck.png' },
  { type: 'bow', image: '/boxes/green_bow.png' },
  { type: 'shoe', image: '/boxes/blue_shoe.png' },
  { type: 'apple', image: '/boxes/red_apple.png' },
  { type: 'shoe', image: '/boxes/green_shoe.png' },
  { type: 'sock', image: '/boxes/blue_sock.png' },
  { type: 'duck', image: '/boxes/red_duck.png' },
  { type: 'hat', image: '/boxes/hat1.png' },
]

export const imagesRound9 = [
  { type: 'hat', image: '/boxes/hat1.png' },
  { type: 'tie', image: '/boxes/blue_tie.png' },
  { type: 'sock', image: '/boxes/red_sock.png' },
  { type: 'duck', image: '/boxes/blue_duck.png' },
  { type: 'scarf', image: '/boxes/green_scarf.png' },
  { type: 'sock', image: '/boxes/green_sock.png' },
  { type: 'apple', image: '/boxes/red_apple.png' },
  { type: 'duck', image: '/boxes/yellow_duck.png' },
  { type: 'scarf', image: '/boxes/red_scarf.png' },
  { type: 'cupcake', image: '/boxes/cupcake4.png' },
  { type: 'apple', image: '/boxes/green_apple.png' },
  { type: 'tie', image: '/boxes/yellow_tie.png' },
  { type: 'apple', image: '/boxes/yellow__apple.png' },
  { type: 'duck', image: '/boxes/green_duck.png' },
  { type: 'hat', image: '/boxes/hat2.png' },
  { type: 'cupcake', image: '/boxes/cupcake2.png' },
  { type: 'scarf', image: '/boxes/blue_scarf.png' },
  { type: 'cupcake', image: '/boxes/cupcake1.png' },
]

export const imagesRound10 = [
  { type: 'pen', image: '/boxes/red_pen.png' },
  { type: 'cactus', image: '/boxes/blue_cactus.png' },
  { type: 'clock', image: '/boxes/green_clock.png' },
  { type: 'heart', image: '/boxes/yellow_heart.png' },
  { type: 'strawberry', image: '/boxes/green_strawberry.png' },
  { type: 'heart', image: '/boxes/green_heart.png' },
  { type: 'tie', image: '/boxes/blue_tie.png' },
  { type: 'pen', image: '/boxes/yellow_pen.png' },
  { type: 'strawberry', image: '/boxes/yellow_strawberry.png' },
  { type: 'pen', image: '/boxes/green_pen.png' },
  { type: 'clock', image: '/boxes/yellow_clock.png' },
  { type: 'cactus', image: '/boxes/green_cactus.png' },
  { type: 'scarf', image: '/boxes/red_scarf.png' },
  { type: 'heart', image: '/boxes/blue_heart.png' },
  { type: 'tie', image: '/boxes/yellow_tie.png' },
  { type: 'clock', image: '/boxes/red_clock.png' },
  { type: 'scarf', image: '/boxes/blue_scarf.png' },
  { type: 'strawberry', image: '/boxes/red_strawberry.png' },
]
