export const mealsRound1Person1 = [
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken2_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'wrong', image: '/waiter-game/Salad2_512.png'},
    { answer: 'correct', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake2_512.png'},
];

export const mealsRound1Person2 = [
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'correct', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken2_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'wrong', image: '/waiter-game/Salad2_512.png'},
    { answer: 'wrong', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake2_512.png'},
];


export const mealsRound2Person1 = [
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'correct', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
    { answer: 'wrong', image: '/waiter-game/meat_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'correct', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish2_512.png'},
];

export const mealsRound2Person2 = [
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
    { answer: 'wrong', image: '/waiter-game/meat_512.png'},
    { answer: 'correct', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'correct', image: '/waiter-game/salad512.png'},
];

export const mealsRound3Person1 = [
    { answer: 'wrong', image: '/waiter-game/steak2_512.png'},
    { answer: 'correct', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake_512.png'},
    { answer: 'correct', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'wrong', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'correct', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
];

export const mealsRound3Person2 = [
    { answer: 'wrong', image: '/waiter-game/steak2_512.png'},
    { answer: 'wrong', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'correct', image: '/waiter-game/salad512.png'},
    { answer: 'correct', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'correct', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
];

export const mealsRound4Person1 = [
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'correct', image: '/waiter-game/cupcake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish2_512.png'},
    { answer: 'correct', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish1_512.png'},
    { answer: 'wrong', image: '/waiter-game/Salad2_512.png'},
    { answer: 'wrong', image: '/waiter-game/meat_512.png'},
    { answer: 'correct', image: '/waiter-game/steak1_512.png'},
    { answer: 'correct', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'wrong', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
];

export const mealsRound4Person2 = [
    { answer: 'correct', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'correct', image: '/waiter-game/dish1_512.png'},
    { answer: 'correct', image: '/waiter-game/Salad2_512.png'},
    { answer: 'wrong', image: '/waiter-game/meat_512.png'},
    { answer: 'wrong', image: '/waiter-game/steak1_512.png'},
    { answer: 'wrong', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'wrong', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'correct', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
];

export const mealsRound5Person1 = [
    { answer: 'correct', image: '/waiter-game/steak2_512.png'},
    { answer: 'wrong', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake2_512.png'},
    { answer: 'correct', image: '/waiter-game/fish_512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'correct', image: '/waiter-game/dish2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish1_512.png'},
    { answer: 'correct', image: '/waiter-game/Salad2_512.png'},
    { answer: 'wrong', image: '/waiter-game/meat_512.png'},
    { answer: 'wrong', image: '/waiter-game/steak1_512.png'},
    { answer: 'wrong', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'wrong', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'wrong', image: '/waiter-game/cake3_512.png'},
    { answer: 'correct', image: '/waiter-game/cupcake3_512.png'},
];

export const mealsRound5Person2 = [
    { answer: 'wrong', image: '/waiter-game/steak2_512.png'},
    { answer: 'wrong', image: '/waiter-game/egg_bacon512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken1_512.png'},
    { answer: 'wrong', image: '/waiter-game/salad512.png'},
    { answer: 'correct', image: '/waiter-game/cupcake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/chicken2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake_512.png'},
    { answer: 'correct', image: '/waiter-game/meat_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish2_512.png'},
    { answer: 'wrong', image: '/waiter-game/cake2_512.png'},
    { answer: 'wrong', image: '/waiter-game/dish1_512.png'},
    { answer: 'wrong', image: '/waiter-game/Salad2_512.png'},
    { answer: 'correct', image: '/waiter-game/steak1_512.png'},
    { answer: 'correct', image: '/waiter-game/hot_dog_512.png'},
    { answer: 'wrong', image: '/waiter-game/peas_carrot512.png'},
    { answer: 'wrong', image: '/waiter-game/chop512.png'},
    { answer: 'correct', image: '/waiter-game/cake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/cupcake3_512.png'},
    { answer: 'wrong', image: '/waiter-game/fish_512.png'},
];